insert into Categories values ('Burger')
insert into Categories values ('Pizza')
insert into Categories values ('Sandwich')
insert into Categories values ('Shake')
insert into Categories values ('Ice-Cream')
insert into Categories values ('Dessert')


insert into Foods values ('Beyond Meat The Beyond Burger', 'https://m.media-amazon.com/images/I/71vzLku02HL._SX679_PIbundle-8,TopRight,0,0_AA679SH20_.jpg', 80, 'The revolutionary plant based burger that looks, cooks, and satisfies like beef.', 1, 1)
insert into Foods values ('Omaha Steaks All Wrapped Up Freezer Loader', 'https://m.media-amazon.com/images/I/816Ng3Rv-1L._SX679_.jpg', 162, 'Founded in 1917, Omaha Steaks has evolved from a small-scale butcher shop in Omaha, Nebraska to world-famous experts in premium beef and gourmet food. Every Omaha Steaks is hand-selected for quality, naturally aged to maximum tenderness, and delivered with perfection. There’s no substitute for the original, and there’s no other steak this good.', 1, 1)
insert into Foods values ('Omaha Steaks 40 Omaha Steaks Burgers', 'https://m.media-amazon.com/images/I/71h2rmcks5L._SX679_.jpg', 240, 'Make your cookout sizzle with this tasty combination of 40 (5 oz.) Omaha Steaks Burgers and 40 (3 oz.) Gourmet Jumbo Franks.', 1, 1)
insert into Foods values ('Burger Master Innovative 8 in 1 Burger Press', 'https://m.media-amazon.com/images/I/81OVwmCUkCL._AC_SX679_.jpg', 30, 'Easily pop out a couple frozen burger patties directly onto the barbecue. The Burger Master keeps them separate and they don’t stick.', 1, 1)
insert into Foods values ('Beef Ground 80/20 Patties', 'https://m.media-amazon.com/images/I/51grqAORSDS._SX679_.jpg', 50, 'Meets standards for animal welfare, feed, and more, so you can know about what you’re buying (and eating)', 1, 1)
insert into Foods values ('Wild Planet Wild Sockeye Salmon, Skinless & Boneless', 'https://m.media-amazon.com/images/I/81g3QsCa2aL._SX679_PIbundle-12,TopRight,0,0_SX679SY453SH20_.jpg', 83, 'HEALTHY OMEGA 3 – Count on this sockeye salmon to provide you with 470mg of EPA and DHA Omega 3 per 2oz serving, supporting your whole-body health. Trans fat is zero', 1, 1)

insert into Foods values ('Chef Boyardee Pepperoni Pizza Maker', 'https://m.media-amazon.com/images/I/81tRfnQNx-L._SX679_.jpg', 39, 'When everyone is hungry and bored, reach for the Chef Boyardee Pepperoni Pizza kit and create a fun, delicious lunch or snack', 1, 2)
insert into Foods values ('Schar - Pizza Crust - Certified Gluten Free', 'https://m.media-amazon.com/images/I/81IZzBrXbfL._SX679_PIbundle-4,TopRight,0,0_AA679SH20_.jpg', 41, 'Weve made it so easy to create an incredible Italian-style pizza at home with Schär Gluten Free Pizza Crusts. The authentic texture and flavor of these Certified Gluten Free pizza crusts is the result of passion, expertise and truly phenomenal ingredients. Simply add sauce, cheese and your favorite toppings, pop them in the oven and in minutes, youll have a homemade masterpiece to share', 1, 2)
insert into Foods values ('Chef Boyardee Cheese Pizza Maker', 'https://m.media-amazon.com/images/I/91ZKTzheJIL._SX679_.jpg', 60, 'Pizza night just got better, thanks to the Chef Boyardee Cheese Pizza maker. Youll love the taste of Italian-flavored tomato sauce in the Chef Boyardee Cheese Pizza maker. When everyone is hungry and bored, reach for the Chef Boyardee Cheese Pizza kit and create a fun, delicious lunch or snack.', 1, 2)
insert into Foods values ('PARMCRISPS Brick Oven Pizza Crisps', 'https://m.media-amazon.com/images/I/81LwfipoUqL._SY679_.jpg', 10, 'Real Cheese Snack', 1, 2)
insert into Foods values ('SCREAMIN SICILIAN PIZZA HOLY PEPPERONI', 'https://m.media-amazon.com/images/I/61qCwspoUoL.jpg', 50, 'WE SUGGEST YOU SELECT SECOND DAY OR EXPEDITED SHIPPING FOR THIS ITEM', 1, 2)
insert into Foods values ('HOME RUN INN PIZZA DELUXE ULTRA THIN', 'https://m.media-amazon.com/images/I/412dI0IozdL.jpg', 40, 'WE SUGGEST YOU SELECT SECOND DAY OR EXPEDITED SHIPPING FOR THIS ITEM', 1, 2)
insert into Foods values ('TOMBSTONE PIZZA ORIGINAL PEPPPERONI', 'https://m.media-amazon.com/images/I/61qtLqEH+BL.jpg', 75, 'MADE WITH 100% REAL CHEESE, 350 CALORIES PER 1/4 PIZZA, MADE WITH PORK, CHICKEN AND BEEF, PRESERVATIVE FREE CRUST', 1, 2)
insert into Foods values ('STOUFFERS PIZZA FRENCH BREAD PEPPERONI FROZEN', 'https://m.media-amazon.com/images/I/51c7RDToFhL.jpg', 46, 'WE SUGGEST YOU SELECT SECOND DAY OR EXPEDITED SHIPPING FOR THIS ITEM. STOUFFERS PIZZA FRENCH BREAD PEPPERONI FROZEN FOOD 11.25 OZ PACK OF 3. PACKAGES MAY BE BROKEN APART FOR COLDER & MORE EFFICIENT SHIPPING', 1, 2)
insert into Foods values ('FRESCHETTA PIZZA BRICK OVEN CRUST PEPPERONI', 'https://m.media-amazon.com/images/I/519nfZ2GjyL.jpg', 69, 'WE SUGGEST YOU SELECT SECOND DAY OR EXPEDITED SHIPPING FOR THIS ITEM, KITCHEN FRESH PIZZA, 100% REAL CHEESE', 1, 2)
insert into Foods values ('CALIFORNIA PIZZA KITCHEN BBQ CHICKEN CRISPY', 'https://m.media-amazon.com/images/I/51e9A+Jra5L.jpg', 80, 'WE SUGGEST YOU SELECT SECOND DAY OR EXPEDITED SHIPPING FOR THIS ITEM, CRISPY THIN CRUST PIZZA, TOPPED WITH BARBEQUED SEASONED GRILLED CHICKEN, RED ONIONS, CILANTRO, MOZZARELLA & HICKORY SMOKED GOUDA CHEESES OVER SWEET & TANGY BBQ SAUCE', 1, 2)
insert into Foods values ('PALERMO PIZZA PRIMO THIN PEPPPERONI', 'https://m.media-amazon.com/images/I/41Yo-+4pHLL.jpg', 30, 'WE SUGGEST YOU SELECT SECOND DAY OR EXPEDITED SHIPPING FOR THIS ITEM', 1, 2)
insert into Foods values ('Nutrisystem', 'https://m.media-amazon.com/images/I/912rtxLt9mL._AC_SX679_PIbundle-4,TopRight,0,0_SH20_.jpg', 47, 'Nutrisystem Feel Good Favorites Thick Crust Pizza, Cheese Value Pack, 4 Pizzas Counted', 1, 2)
insert into Foods values ('HOME RUN INN PIZZA CLASSIC UNCURED PEPPERONI', 'https://m.media-amazon.com/images/I/61b2xUa4uqL.jpg', 63, 'WE SUGGEST YOU SELECT SECOND DAY OR EXPEDITED SHIPPING FOR THIS ITEM, PREMIUM PIZZERIA, CLASSIC UNCURED PEPPERONI', 1, 2)
insert into Foods values ('Golden Home Ultra Thin 3 Piece', 'Golden Home Ultra Thin 3 Piece', 10, 'Golden Home Ultra Thin 3 Piece Pizza Crust, 14.25 Ounce', 1, 2)
insert into Foods values ('Mama Mary', 'https://m.media-amazon.com/images/I/91SeJqu7olL._SX679_.jpg', 15, 'For more than 25 s, Mama Marys Gourmet pizza crusts have been providing families with a home-baked, in-home dining experience that is unmatched by delivery or frozen pizza.', 1, 2)
insert into Foods values ('Pizza Cubana', 'https://m.media-amazon.com/images/I/516AyR2R8JL.jpg', 8, 'Quick, Easy, and Fast! High Quality Oven-Ready Pizza. Bringing The Taste Of Cuba To Live In Minutes. Open The Box, Place Pizza In Oven At 450 Degrees, Bake For 5-7 Minutes, And Get Ready For Your Taste Buds To Be Satisfied.', 1, 2)
insert into Foods values ('Chef Boyardee', 'https://m.media-amazon.com/images/I/31cQENZkTDL.jpg', 20, 'Chef Boyardee Pizza Sauce with Cheese has the authentic flavor that everyone loves. Rich, Italian-flavored tomato sauce and zesty cheese take the hassle out of making pizza at home. Add Chef Boyardee Pizza Sauce with Cheese to ready-made dough, and pizza is ready in minutes. Chef Boyardee Pizza Sauce with Cheese makes pizza night quick and easy.', 1, 2)
insert into Foods values ('Francine Preparation', 'https://m.media-amazon.com/images/I/31FoJrhDVaL.jpg', 10, 'Francine preparation pizza 520g', 1, 2)
insert into Foods values ('HOT POCKETS FROZEN SANDWICHES PEPPERONI', 'https://m.media-amazon.com/images/I/51Y6lGCwHnL.jpg', 20, 'WE SUGGUEST YOU SELECT SECOND DAY OR EXPEDITED SHIPPING FOR THIS ITEM', 1, 2)
insert into Foods values ('Gourmet Hawaiian', 'https://m.media-amazon.com/images/I/51YWnvZnbAL.jpg', 115, 'Enjoy the combination of sweet and salty flavors, tempered by juicy bursts of fruit that comes with a slice of a Hawaiian pie, Perfect to have on hand or to send to friends and family to enjoy, Please note that any item temporarily out of stock will be substituted with a similar item of equal value', 1, 2)
insert into Foods values ('Gluten-Free Italian Calzones', 'https://m.media-amazon.com/images/I/71f0Iw16AZS._SX679_.jpg', 20, 'It’s è delizioso! We are delivering the perfect blend of Italian seasonings… garlic, onions, oregano & more with our versatile Calzone’s, Pizza Pockets or Pizza Rolls! or dip in Mom’s Place Quick & Classic Pizza Sauce! Serve with Mom’s Place Garlic Knots, Cheese Sticks & CinnaSticks! Your options are endless with this carefully-crafted, non-GMO, preservative free, gluten free, dairy free, etc…', 1, 2)
insert into Foods values ('Schär Pizza', 'https://images-na.ssl-images-amazon.com/images/I/51ELzlgU1mL._SX300_SY300_QL70_FMwebp_.jpg', 11, 'Schär Pizza , 1er Pack (1 x 300 g Packung)', 1, 2)
insert into Foods values ('Salvatores Gourmet Pizza Kit', 'https://m.media-amazon.com/images/I/81cDneLyYKL._SY679_.jpg', 23, 'Make a Hall of Fame gourmet fresh hot pizza with the family with Salvatores Pizza Combo Pack - featuring the Salvatores Pizza Dough Mix and the Salvatores Pizza Sauce. Salvatores Pizza for over 60 years has been a Buffalo and Western New York Favorite serving up Pies from our original restaurant in 1955 and today at Fairs and festivals like the Erie County Fair', 1, 2)
insert into Foods values ('Napolina Pizzeria Pizza Bases', 'https://m.media-amazon.com/images/I/51WVHgTWi6L.jpg', 39, '2 Large Light and Crispy Pizza Bases. Ready in 10 minutes. Make your own delicious pizza with Napolina Pizza topping. Light and crispy.READY IN 10 MINUTES. MAKE YOUR OWN DELICIOUS PIZZA WITH NAPOLINA PIZZA TOPPING.PRODOTTO IN ITALIA.', 1, 2)

insert into Foods values ('Banh Trang Spring Roll Wrapper', 'https://m.media-amazon.com/images/I/81zSMFReP+L._SX679_.jpg', 70, 'Banh Trang spring roll wrapper, 12-ounce (pack of 8)are made from rice flour, salt and water and sometimes from tapioca flour. Rice sheet wrappers are a bit softer and more pliable when soaked. The wrappers are soaked lightly before use then ingredients are rolled up in the wrappers and served with a variety of sauces.', 1, 3)
insert into Foods values ('Sandwich Wrapper', 'https://m.media-amazon.com/images/I/610T4kA+vaL._AC_SY879_.jpg', 6, 'Sandwich Wrapper Home Breakfast Burrito Man', 1, 3)

insert into Accounts values ('Admin', 999999999999, 'Admin99@gmail.com', '12345', 1, 1)
insert into Accounts values ('User', 0981987625, 'User1@gmail.com', '1', 1, 1)

insert into Orders values (2, GETDATE(), 'Yen Ninh-Yen Khanh-Ninh Binh', 1, 1, 2)
insert into Orders values (1, GETDATE(), 'Yen Ninh-Yen Khanh-Ninh Binh', 1, 2, 2)
insert into Orders values (3, GETDATE(), 'Yen Ninh-Yen Khanh-Ninh Binh', 1, 3, 2)

insert into Carts values (2, 1, 2)
insert into Carts values (3, 2, 2)
insert into Carts values (2, 3, 2)
insert into Carts values (1, 4, 2)

insert into Wishs values (1, 2)
insert into Wishs values (2, 2)
insert into Wishs values (3, 2)
insert into Wishs values (4, 2)